using System.Net;

using FluentValidation;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using PaymentGateway.Api.Filters;
using PaymentGateway.Api.Interfaces;
using PaymentGateway.Api.Models;
using PaymentGateway.Api.Models.Merchant;

namespace PaymentGateway.Api.Controllers;

[Route("api/[controller]")]
[ApiController]
public partial class PaymentsController : ControllerBase // inheriting from controllerbase as we dont need views
{
    private readonly IPaymentsRepository _paymentsRepository;
    private readonly IValidator<PaymentRequest> _paymentRequestValidator;
    private readonly IPaymentMetrics _paymentMetrics;
    private readonly ILogger<PaymentsController> _logger;
    private readonly IAcquiringBank _acquiringBank;

    public PaymentsController(IPaymentsRepository paymentsRepository, 
        IValidator<PaymentRequest> paymentRequestValidator,
        IPaymentMetrics paymentMetrics,
        ILogger<PaymentsController> logger,
        IAcquiringBank acquiringBank)
    {
        _paymentsRepository = paymentsRepository;
        _paymentRequestValidator = paymentRequestValidator;
        _paymentMetrics = paymentMetrics;
        _logger = logger;
        _acquiringBank = acquiringBank;
    }


    // Allow only users with merchant claim to start a payment
    [Authorize(Roles = "Merchant")]
    [IdempotencyKey] // custom filter to handle idempotency key validation and processing
    [HttpPost]
    public async Task<ActionResult<PaymentResponse>> PostPaymentAsync([FromBody] PaymentRequest request)
    {
        PaymentsLog.ReceivedPaymentRequest(_logger, request.Amount, request.Currency);

        // validate request
        var result = _paymentRequestValidator.Validate(request);
        if (!result.IsValid)
        {
            PaymentsLog.PaymentValidationFailure(_logger, string.Join(", ", result.Errors.Select(e => e.ErrorMessage)));
            _paymentMetrics.RecordPaymentStatus(PaymentStatus.Declined); 
            return BadRequest(result.Errors);
        }

        // send payment to acquiring bank
        var paymentResponse = await _acquiringBank.SendPayment(new Models.AcquiringBank.PaymentRequest
        {
            Amount = request.Amount,
            Currency = request.Currency,
            CardNumber = request.CardNumber,
            ExpiryDate = request.ExpiryMonth + "/" + request.ExpiryYear
        });

        // save payment to repository 
        // Id is generated here for simplicity, but in a real application it would likely be
        // generated by the database or a separate service.
        var payment = new Payment
        {
            Amount = request.Amount,
            Currency = request.Currency,
            CardNumber = request.CardNumber[^4..],
            ExpiryMonth = request.ExpiryMonth,
            ExpiryYear = request.ExpiryYear,
            CVV = request.CVV,
            Status = paymentResponse.Status,
            AuthorizationCode = paymentResponse.PaymentResponse?.AuthorizationCode ?? ""
        };

        await _paymentsRepository.Add(payment);

        var statusCode = paymentResponse.Status switch
        {
            PaymentStatus.Authorized => HttpStatusCode.OK,
            PaymentStatus.Declined => HttpStatusCode.BadRequest, //HttpStatusCode.PaymentRequired,
            PaymentStatus.Rejected => HttpStatusCode.BadRequest, //HttpStatusCode.PaymentRequired,
            _ => HttpStatusCode.BadRequest
        };

        PaymentsLog.PaymentProcessedStatus(_logger, paymentResponse.Status, payment.Id);
        _paymentMetrics.RecordPaymentStatus(paymentResponse.Status);

        return StatusCode((int)statusCode, new PaymentResponse
        {
            Id = payment.Id,
            Amount = request.Amount,
            Currency = request.Currency,
            CardNumberLastFour = request.CardNumber[^4..],
            ExpiryMonth = request.ExpiryMonth,
            ExpiryYear = request.ExpiryYear,
            Status = paymentResponse.Status.ToString(),
        });
    }

    [HttpGet("{id:guid}")]
    public async Task<ActionResult<PaymentResponse?>> GetPaymentAsync(Guid id)
    {
        PaymentsLog.ReceivedGetPaymentRequest(_logger, id);
        //todo add metrics for this endpoint as well
        var payment = await _paymentsRepository.Get(id);

        if (payment == null)
        {
            PaymentsLog.PaymentNotFound(_logger, id);
            return NotFound();
        }

        PaymentsLog.PaymentFound(_logger, id);
        return Ok(new PaymentResponse
        {
            Id = payment.Id,
            Amount = payment.Amount,
            Currency = payment.Currency,
            CardNumberLastFour = payment.CardNumber,
            ExpiryMonth = payment.ExpiryMonth,
            ExpiryYear = payment.ExpiryYear,
            Status = payment.Status.ToString(),
        });
    }
}